channels:
- conda-forge
dependencies:
- coverage
- codacy-coverage
- cloudpickle =3.0.0
- gitpython =3.1.40
- h5io_browser =0.0.5
- h5py =3.10.0
- jinja2 =3.1.2
- numpy =1.26.3
- pandas =2.1.4
- pint =0.23
- psutil =5.9.7
- pyfileindex =0.0.20
- pysqa =0.1.9
- pytables =3.9.2
- sqlalchemy =2.0.25
- tqdm =4.66.1
- traitlets =5.14.1
