channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- numpy
- cloudpickle =3.0.0
- gitpython =3.1.41
- h5io_browser =0.0.7
- h5py =3.10.0
- jinja2 =3.1.3
- numpy =1.26.3
- pandas =2.2.0
- pint =0.23
- psutil =5.9.8
- pyfileindex =0.0.21
- pysqa =0.1.13
- pytables =3.9.2
- sqlalchemy =2.0.25
- tqdm =4.66.1
- traitlets =5.14.1
