channels:
- conda-forge
dependencies:
- nbsphinx
- gitpython
- h5io
- h5py
- jinja2
- numpy
- pandas
- pint
- psutil
- pyfileindex
- pysqa
- pytables
- sqlalchemy
- tqdm
- traitlets
- sphinx-rtd-theme
